fix

diff --git a/RHEL/neovim b/RHEL/neovim
--- a/RHEL/neovim
+++ b/RHEL/neovim
@@ -1,51 +1,55 @@
 #!/usr/bin/env bash
-RELEASE="$(grep -RPho '(?<=\bNAME=").*?(?=")' -R /etc/*-release)"
-case ${RELEASE} in
-"Ubuntu")
-  sudo apt purge vim vim-nox vim-tiny --autoremove -y
-  sudo apt install python3-{dev,pip,venv} curl build-essential \
-    cmake ninja-build gettext unzip software-properties-common \
-    git -y --no-install-recommends
-  ;;
-"Rocky Linux" | "AlmaLinux")
-  sudo dnf remove vim{,-minimal} python3-neovim -yq
-  sudo dnf install gcc-c++ make cmake ShellCheck git ninja-build -yq --setopt=install_weak_deps=False
-  sudo dnf install python3-{virtualenv,wheel,pip,devel,jedi} --setopt=install_weak_deps=False -y
-  ;;
-esac
 
-rm -f "$(which nvim)"
+if [[ $USER = 'root' ]]; then
 
-src_dir="/opt/neovim"
+  RELEASE="$(grep -RPho '(?<=\bNAME=").*?(?=")' -R /etc/*-release)"
+  case ${RELEASE} in
+  "Ubuntu")
+    sudo apt purge vim vim-nox vim-tiny --autoremove -y
+    sudo apt install python3-{dev,pip,venv} curl build-essential \
+      cmake ninja-build gettext unzip software-properties-common \
+      git -y --no-install-recommends
+    ;;
+  "Rocky Linux" | "AlmaLinux")
+    sudo dnf remove vim{,-minimal} python3-neovim -yq
+    sudo dnf install gcc-c++ make cmake ShellCheck git ninja-build -yq --setopt=install_weak_deps=False
+    sudo dnf install python3-{virtualenv,wheel,pip,devel,jedi} --setopt=install_weak_deps=False -y
+    ;;
+  esac
 
-rm -rf "${src_dir}"
-mkdir -p "${src_dir}"
+  rm -f "$(which nvim)"
 
-git clone https://github.com/neovim/neovim.git "${src_dir}" && {
-  cd "${src_dir}"
-} || exit ${LINENO}
+  src_dir="/opt/neovim"
 
-git checkout stable -q
+  rm -rf "${src_dir}"
+  mkdir -p "${src_dir}"
 
-make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr" -j "$(nproc)" || {
-  printf '\e[1;31m%s\e[0m\n' "Error on compile"
-  exit ${LINENO}
-}
-sudo make install || exit ${LINENO}
-cd - || exit ${LINENO}
+  git clone https://github.com/neovim/neovim.git "${src_dir}" && {
+    cd "${src_dir}"
+  } || exit ${LINENO}
 
-nvim_binary="$(which nvim)"
+  git checkout stable -q
 
-make_alternatives() {
-  local alternative
-  for alternative in vi vim; do
-    update-alternatives --install /usr/bin/$alternative $alternative "${nvim_binary}" 100
-    update-alternatives --set $alternative "${nvim_binary}"
-  done
-  update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 1000
-}
+  make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr" -j "$(nproc)" || {
+    printf '\e[1;31m%s\e[0m\n' "Error on compile"
+    exit ${LINENO}
+  }
+  sudo make install || exit ${LINENO}
+  cd - || exit ${LINENO}
 
-make_alternatives || exit ${LINENO}
+  nvim_binary="$(which nvim)"
+
+  make_alternatives() {
+    local alternative
+    for alternative in vi vim; do
+      update-alternatives --install /usr/bin/$alternative $alternative "${nvim_binary}" 100
+      update-alternatives --set $alternative "${nvim_binary}"
+    done
+    update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 1000
+  }
+
+  make_alternatives || exit ${LINENO}
+fi
 
 PYTHON_VERSION='3.11'
 
